using BenchmarkDotNet.Attributes;
using RePacker.Buffers;
using RePacker.Builder;

namespace RePacker.Benchmarks
{
    [MemoryDiagnoser]
    public class GeneralBenches
    {
        ReBuffer buffer = new ReBuffer(1 << 16);

        /* netcoreapp3.1
|                       Method |         Mean |     Error |    StdDev |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------- |-------------:|----------:|----------:|--------:|------:|------:|----------:|
|            BenchSizeOfSimple |     37.69 us |  0.129 us |  0.121 us |       - |     - |     - |         - |
|           BenchSizeOfComplex |     98.46 us |  0.257 us |  0.228 us |       - |     - |     - |         - |
|         BenchSizeOfHasString |    157.61 us |  0.445 us |  0.394 us |       - |     - |     - |       3 B |
|            BenchSizeOfString |    150.42 us |  0.355 us |  0.332 us |       - |     - |     - |         - |
|       BenchSizeOfStringLarge |  1,575.57 us |  1.703 us |  1.422 us |       - |     - |     - |         - |
| BenchSizeOfReallyStringLarge | 18,887.61 us | 53.794 us | 50.319 us |       - |     - |     - |         - |
|       BenchSizeOfArrayString | 17,481.60 us | 32.766 us | 29.046 us | 93.7500 |     - |     - |  320000 B |
        */

        /* net4.6.1
|                       Method |          Mean |      Error |     StdDev |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------- |--------------:|-----------:|-----------:|--------:|------:|------:|----------:|
|            BenchSizeOfSimple |      33.63 us |   0.097 us |   0.091 us |       - |     - |     - |         - |
|           BenchSizeOfComplex |      92.78 us |   0.272 us |   0.254 us |       - |     - |     - |         - |
|         BenchSizeOfHasString |     247.27 us |   1.016 us |   0.950 us |       - |     - |     - |         - |
|            BenchSizeOfString |     180.00 us |   0.529 us |   0.495 us |       - |     - |     - |         - |
|       BenchSizeOfStringLarge |  16,284.28 us |  38.607 us |  36.113 us |       - |     - |     - |         - |
| BenchSizeOfReallyStringLarge | 176,458.80 us | 491.360 us | 459.618 us |       - |     - |     - |         - |
|       BenchSizeOfArrayString |  21,040.38 us |  95.306 us |  89.150 us | 93.7500 |     - |     - |  321029 B |
        */

        [Benchmark]
        public void BenchSizeOfSimple()
        {
            int val = 10;
            for (int i = 0; i < 10_000; i++)
            {
                int size = RePacking.SizeOf(ref val);
            }
        }

        [Benchmark]
        public void BenchSizeOfComplex()
        {
            var val = new Parent();
            for (int i = 0; i < 10_000; i++)
            {
                int size = RePacking.SizeOf(ref val);
            }
        }

        StructWithString structWithString = new StructWithString { String1 = "hello" };

        [Benchmark]
        public void BenchSizeOfHasString()
        {
            for (int i = 0; i < 10_000; i++)
            {
                int size = RePacking.SizeOf(ref structWithString);
            }
        }

        [Benchmark]
        public void BenchSizeOfString()
        {
            var val = "hello";

            for (int i = 0; i < 10_000; i++)
            {
                int size = RePacking.SizeOf(ref val);
            }
        }

        [Benchmark]
        public void BenchSizeOfStringLarge()
        {
            var val =
@"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.";

            for (int i = 0; i < 10_000; i++)
            {
                int size = RePacking.SizeOf(ref val);
            }
        }

        static string reallyLongString =
@"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae lorem libero. Curabitur pellentesque dignissim est, eget dignissim lorem semper eget. Mauris scelerisque suscipit est id lobortis. Vestibulum ac lectus nec velit facilisis bibendum. Ut efficitur eget tellus id vulputate. Vivamus id velit tortor. Sed nec ultrices massa, ac gravida leo. Integer et tortor sodales, imperdiet lorem vitae, gravida orci. In metus tellus, pellentesque a dapibus quis, ultricies et tellus. Aliquam viverra, elit in luctus finibus, neque diam facilisis est, ac porta nunc massa nec magna. In vulputate maximus ipsum, pharetra suscipit nisl lobortis ut. Etiam consectetur ullamcorper vestibulum. Sed non ullamcorper neque. Etiam sodales pharetra lectus quis porttitor. Maecenas porta, justo sit amet tincidunt euismod, sem nulla ornare metus, ac fringilla diam nunc tincidunt nibh. Cras varius arcu at sapien dapibus, ac maximus purus consectetur.
Aliquam eu ullamcorper mi, et accumsan enim. Phasellus viverra metus ac risus tristique ultrices. Aenean sit amet diam nisi. Vivamus sagittis justo sodales lacus fringilla, id vehicula odio sagittis. Quisque in ante ut turpis cursus maximus. Sed mattis enim et libero rhoncus blandit. Aenean nec sapien vehicula, dignissim diam sit amet, porttitor ipsum. Morbi vestibulum in nisl quis commodo. Proin non fringilla dui. Donec blandit vestibulum nibh, vitae ullamcorper felis euismod sit amet. Maecenas ac malesuada metus. Nunc rhoncus neque eu turpis malesuada efficitur.
Quisque in enim ligula. Donec velit ex, faucibus sodales enim sed, egestas suscipit nisl. Ut dignissim massa non tristique interdum. Ut non nunc consectetur, congue enim eu, aliquam diam. Curabitur viverra eget neque sed porta. Phasellus condimentum, elit in gravida consectetur, leo libero malesuada justo, sed iaculis erat augue ac augue. Nullam vitae pharetra mauris. Nullam vestibulum dui sed eros laoreet sodales. In aliquet augue ut diam placerat, at malesuada nulla dapibus. Aliquam ut quam vitae dui cursus tempor non sit amet lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam aliquet, felis ac tristique ultrices, tortor sem interdum neque, nec commodo metus arcu nec leo. Etiam et quam tristique, viverra augue quis, fringilla leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent odio lacus, cursus sed nunc ac, ornare ornare libero.
Etiam laoreet arcu vel mauris volutpat volutpat. Phasellus pretium ornare sapien, at fermentum dolor ultrices eu. Maecenas condimentum libero at magna placerat, id sagittis mauris facilisis. Proin vulputate ornare dui in ullamcorper. Phasellus aliquam justo velit, at posuere neque laoreet vel. Donec et velit non mauris iaculis varius quis facilisis ante. Nunc facilisis lacus dui, porta facilisis ipsum pulvinar at.
Praesent purus dolor, accumsan et urna quis, tincidunt volutpat velit. Sed auctor ex quam, posuere dapibus lectus condimentum ut. Phasellus placerat, felis et luctus eleifend, odio mi pulvinar nunc, nec scelerisque ante lorem ut enim. Praesent efficitur lobortis aliquet. Praesent sollicitudin vel augue at placerat. Curabitur sem nisi, interdum sed consequat at, dictum eget leo. Sed et venenatis orci, id ornare quam. Cras et faucibus tortor, ac accumsan ligula. Fusce cursus, lacus a mattis ultrices, leo nulla semper nisi.";

        [Benchmark]
        public void BenchSizeOfReallyStringLarge()
        {
            for (int i = 0; i < 10_000; i++)
            {
                int size = RePacking.SizeOf(ref reallyLongString);
            }
        }

        static string[] stringArray = new string[] {
                "hello","hello","hello","hello","hello","hello","hello",
                "hello","hello","hello","hello","hello","hello","hello",
                "hello","hello","hello","hello","hello","hello","hello",
                "hello","hello","hello","hello","hello","hello","hello",
                "hello","hello","hello","hello","hello","hello","hello",
                "hello","hello","hello","hello","hello","hello","hello",
                "hello","hello","hello","hello","hello","hello","hello",
                "hello","hello","hello","hello","hello","hello","hello",
            };

        [Benchmark]
        public void BenchSizeOfArrayString()
        {
            for (int i = 0; i < 10_000; i++)
            {
                int size = RePacking.SizeOf(ref stringArray);
            }
        }
    }
}