name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Test-Build:
      run: dotnet build --framework netcoreapp3.1 -c Debug RePacker.Tests/RePacker.Tests.csproj
    - name Unsafe-Test-Build:
      run: dotnet build --framework netcoreapp3.1 -c Debug RePacker.Unsafe.Tests/RePacker.Unsafe.Tests.csproj

    - name: Test
      run: dotnet test --framework netcoreapp3.1 RePacker.Tests/RePacker.Tests.csproj --no-build --verbosity normal
    - name: Unsafe-Test
      run: dotnet test --framework netcoreapp3.1 RePacker.Unsafe.Tests/RePacker.Unsafe.Tests.csproj --no-build --verbosity normal
