name: Unity-Tests

on: [push]

jobs:
  testRunnerInPlayMode:
    name: PlayMode Tests
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#      - name: Add msbuild to PATH
#        uses: microsoft/setup-msbuild@v1.0.2
#
#      - name: Setup NuGet
#        uses: NuGet/setup-nuget@v1.0.5
#      - name: nuget restore
#        run: nuget restore "./RePacker.Unity/RePacker.Unity.csproj"
#        
#      - name: Build RePacker
#        run: msbuild "./RePacker.Unity/RePacker.Unity.csproj" /p:TargetFrameworkVersion=v4.6.1;configuration=Unity
#      - name: Move RePacker DLLs
#        run: |
#          mv ./RePacker.Unity/bin/Unity/net4.6.1/RePacker.dll ./RePacker.Unity.Tests/Assets/RePacker/RePacker.dll
#          mv ./RePacker.Unity/bin/Unity/net4.6.1/RePacker.Unsafe.dll ./RePacker.Unity.Tests/Assets/RePacker/RePacker.Unsafe.dll
#          mv ./RePacker.Unity/bin/Unity/net4.6.1/RePacker.Unity.dll ./RePacker.Unity.Tests/Assets/RePacker/RePacker.Unity.dll

      - name: Activate license
        uses: MirrorNG/unity-runner@3.1.0
        with:
          entrypoint: /activate.sh

      - name: Run tests
        id: playModeTests
        uses: MirrorNG/unity-runner@3.1.0
        with:
          args: -runTests -projectPath ./RePacker.Unity.Tests/ -testPlatform PlayMode -testResults results.xml

      - name: Process Results
        shell: bash
        run: |
          ./RePacker.Unity.Tests/process_results.sh -i ./RePacker.Unity.Tests/TestResults/results.xml > results.txt
          cat results.txt

      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
            name: PlayMode Test Results
            path: results.txt