name: Unity-Tests

on: [push]

jobs:
  testRunnerInEditMode:
    name: EditMode Tests
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build RePacker
        shell: bash
        run: |
          original_path=`pwd`
          echo "Building RePacking project..."
          build_path=`realpath ../RePacker.Unity/`
          cd `dirname $build_path/RePacker.Unity/`
          ./build.bat
          echo "Copying DLLs to Unity project..."
          cd `dirname $original_path/RePacker.Unity.Tests/`
          cp ../RePacker.Unity/bin/Unity/net4.6.1/RePacker.dll ./Assets/RePacker/RePacker.dll
          cp ../RePacker.Unity/bin/Unity/net4.6.1/RePacker.Unsafe.dll ./Assets/RePacker/RePacker.Unsafe.dll
          cp ../RePacker.Unity/bin/Unity/net4.6.1/RePacker.Unity.dll ./Assets/RePacker/RePacker.Unity.dll

      - name: Activate license
        uses: MirrorNG/unity-runner@3.1.0
        with:
          entrypoint: /activate.sh

      - name: Run tests
        uses: MirrorNG/unity-runner@3.1.0
        id: editModeTests
        with:
          args: -runTests -projectPath ./RePacker.Unity.Tests/ -testPlatform EditMode -testResults results.xml

      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
            name: EditMode Test Results
            path: results.xml

  testRunnerInPlayMode:
    name: PlayMode Tests
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build RePacker
        shell: bash
        run: |
          original_path=`pwd`
          echo "Building RePacking project..."
          build_path=`realpath ../RePacker.Unity/`
          cd `dirname $build_path/RePacker.Unity/`
          ./build.bat
          echo "Copying DLLs to Unity project..."
          cd `dirname $original_path/RePacker.Unity.Tests/`
          cp ../RePacker.Unity/bin/Unity/net4.6.1/RePacker.dll ./Assets/RePacker/RePacker.dll
          cp ../RePacker.Unity/bin/Unity/net4.6.1/RePacker.Unsafe.dll ./Assets/RePacker/RePacker.Unsafe.dll
          cp ../RePacker.Unity/bin/Unity/net4.6.1/RePacker.Unity.dll ./Assets/RePacker/RePacker.Unity.dll

      - name: Activate license
        uses: MirrorNG/unity-runner@3.1.0
        with:
          entrypoint: /activate.sh

      - name: Run tests
        uses: MirrorNG/unity-runner@3.1.0
        id: playModeTests
        with:
          args: -runTests -projectPath ./RePacker.Unity.Tests/ -testPlatform PlayMode -testResults results.xml

      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
            name: PlayMode Test Results
            path: results.xml